# Generated by Django 4.2.7 on 2023-11-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Login', '0003_remove_userprofile_user_userprofile_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
    ]
