# Generated by Django 4.2.7 on 2023-11-24 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0004_alter_userprofile_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
