# Generated by Django 4.2.7 on 2023-11-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCuenta',
            fields=[
                ('old_id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('new_id', models.IntegerField(blank=True, null=True)),
                ('old_balance', models.IntegerField(blank=True, null=True)),
                ('new_balance', models.IntegerField(blank=True, null=True)),
                ('old_iban', models.IntegerField(blank=True, null=True)),
                ('new_iban', models.IntegerField(blank=True, null=True)),
                ('old_type', models.CharField(blank=True, max_length=45, null=True)),
                ('new_type', models.CharField(blank=True, max_length=45, null=True)),
                ('user_action', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria_cuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.TextField()),
                ('employee_surname', models.TextField()),
                ('employee_hire_date', models.TextField()),
                ('employee_dni', models.TextField(db_column='employee_DNI')),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Marcatarjeta',
            fields=[
                ('marca', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'marcaTarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('branch_id', models.AutoField(primary_key=True, serialize=False)),
                ('branch_number', models.BinaryField()),
                ('branch_name', models.TextField()),
                ('branch_address_id', models.IntegerField()),
            ],
            options={
                'db_table': 'sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocliente',
            fields=[
                ('tipo_cli', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipoCliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipocuenta',
            fields=[
                ('tipo_cuen', models.CharField(blank=True, max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipoCuenta',
                'managed': False,
            },
        ),
    ]
