# Generated by Django 4.2.7 on 2023-11-24 22:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Prestamos', '0002_alter_prestamo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9]{8}$')]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='loan_type',
            field=models.TextField(choices=[('PERSONAL', 'Personal'), ('HIPOTECARIO', 'Hipotecario'), ('PRENDARIO', 'Prendario')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='prestamo',
            table=None,
        ),
    ]
