# Generated by Django 4.2.7 on 2023-11-24 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0003_alter_prestamo_customer_id_alter_prestamo_loan_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='customer_id',
            new_name='customer_id_id',
        ),
    ]
