# Generated by Django 4.2.7 on 2023-11-24 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0004_rename_customer_id_prestamo_customer_id_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='customer_id_id',
            new_name='customer_id',
        ),
    ]
