# Generated by Django 4.2.7 on 2023-11-24 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Prestamos', '0005_rename_customer_id_id_prestamo_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente'),
        ),
    ]
