# Generated by Django 4.2.7 on 2023-11-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0006_alter_prestamo_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='loan_total',
            field=models.IntegerField(),
        ),
    ]
